name: Intialize Database

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  init_db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: abhinaysikarwar/banking-app-2-Tier
          ref: main

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::949678235787:role/github-action-deploy-policy
          aws-region: us-east-1

      - name: Upload file on s3
        run: |
          aws s3 mb s3://s3-lakhan-bucket --region us-east-1 2>/dev/null || true
          aws s3 cp init.sql s3://s3-lakhan-bucket/init.sql
          aws s3 cp init.py s3://s3-lakhan-bucket/init.py
          echo "File Uploaded to Bucket..✅"

      - name: Initializing Database on RDS using Ec2
        id: init
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:APP,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "aws s3 cp s3://s3-lakhan-bucket/init.sql /tmp/init.sql",
              "aws s3 cp s3://s3-lakhan-bucket/init.py /tmp/init.py",
              "python3 /tmp/init.py || exit 1",
              "rm /tmp/init.py"
            ]}' \
            --query 'Command.CommandId' \
            --output text \
            --region us-east-1)
          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT

      - name: Show Results
        run: |
          sleep 30

          aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --details \
            --region us-east-1 \
            --output text

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text \
            --region us-east-1)

          [ "$FAILED" -gt 0 ] && \
            echo "::error::Database Creation Failed $FAILED instance(s)!" && \
            exit 1

          echo "✅ Database Created Successfully"